### ISSUE TITLE
Assumes ~/.m2 directory

### ISSUE THREAD

**Issue by jdelamare** [DavidWhitlock/PortlandStateJavaGettingStarted#2]
Consider placing the following command in the README.md:
```
mkdir ~/.m2
```
This issue is in this [section](https://github.com/DavidWhitlock/PortlandStateJavaGettingStarted#what-do-i-need-to-do-before-i-can-use-this-repository).

**Comment by DavidWhitlock** [comment]
Hey, @jdelamare.  Thanks for mentioning this.  I added it in https://github.com/DavidWhitlock/PortlandStateJavaGettingStarted/commit/d6811126f2ef2a32eff0ba04db5c2a25200d538a  What do you think?

**Comment by jdelamare** [comment]
I believe that solves the issue, thank you for asking.
