### ISSUE TITLE
"Getting Started with Java" link to ~whitlock is broken

### ISSUE THREAD

**Issue by abluescarab** [DavidWhitlock/PortlandStateJavaGettingStarted#38]
I mentioned this during class and the issue is also present on the repo, so I'm opening an issue. In the [README](https://github.com/DavidWhitlock/PortlandStateJavaGettingStarted#getting-started-with-advanced-programming-with-java) the link to "Getting Started with Java" is broken, and there is also a link on the ~whitlock site.
![image](https://user-images.githubusercontent.com/5298903/175193048-6ffe572a-0cd6-462d-bca5-efa06cee2f82.png)

**Comment by DavidWhitlock** [comment]
Thank you for pointing that out.

I removed the reference to the outdates "Getting Started with Java" slide and screencast in https://github.com/DavidWhitlock/PortlandStateWebsite/commit/6fc5c8badf2d28a4c85545c4717d690dd7c257b3
