### ISSUE TITLE
Update repository to template repository

### ISSUE THREAD

**Issue by kesquerra** [DavidWhitlock/PortlandStateJavaGettingStarted#44]
If this repository was updated to a template repository, the students could create a repository of the current file structure without it being forked on default. 
This could reduce the complexity of initially creating the student's private repository (as forking must be public), and subsequent pair programming repos (as only one fork per user is allowed).

Differences (from [Github](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template)):
Creating a repository from a template is similar to forking a repository, but there are important differences:
- A new fork includes the entire commit history of the parent repository, while a repository created from a template starts with a single commit.
- Commits to a fork don't appear in your contributions graph, while commits to a repository created from a template do appear in your contribution graph.
- A fork can be a temporary way to contribute code to an existing project, while creating a repository from a template starts a new project quickly.

[Template Repository Github Instructions](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository)

[Example Template Repository](https://github.com/kesquerra/PortlandStateJavaPairProgramming)
The example template repo shows the 'Use this template' button in the top right which allows for quick repos from the current structure.

**Comment by DavidWhitlock** [comment]
I had no idea that template repositories in GitHub were a thing!  Thank you very much for bringing it to my attention.  I will definitely investigate template repositories and likely use them for the next time I teach.

**Comment by kesquerra** [comment]
Not a problem! I think they're fairly new, or at least I've only noticed them popping up more often recently. They are super convenient and seemed like a good application for this.
